### ISSUE TITLE
Stopped Receiving Energy Updates with HA 2023.8.1

### ISSUE THREAD

**Issue by rjsmith0** [jkeljo/hacs-greeneye-monitor#31]
Home Assistant version: 2023.8.1

HACS version: 1.32.1

hacs-greeneye-monitor version: 2023.8.6

After upgrading HA to 2023.8.1, I stopped receiving energy readings.   I saw the issue initially with hacs-greeneye-monitor 2023.5.30 and it persisted after upgrading to hacs-greeneye-monitor 2023.8.6.  I hadn't touched any of my configuration settings on the GEM or HA configuration and I am receiving voltage, power and current readings without issue.  I did try resetting my counters on the GEM with no change.

<img width="229" alt="image" src="https://github.com/jkeljo/hacs-greeneye-monitor/assets/29410891/d57f31a5-54ca-406f-b952-ca493b8b3254">

<img width="617" alt="image" src="https://github.com/jkeljo/hacs-greeneye-monitor/assets/29410891/939dbc9a-3c60-46c9-a037-c8f4e87eb99c">

**Comment by nivfreak** [comment]
I am in the same boat, getting voltage/current readings, but no power. 

My setup was fresh. I set it up using packet format 4 (Bin48-NET-Time). Same software and firmware versions. 

I'm going to toy around with different packet formats. I didn't find any documentation that specified what format to use, but I may have missed it!

![image](https://github.com/jkeljo/hacs-greeneye-monitor/assets/271317/e8abb88b-8bbd-42dd-b810-88672a33a145)

**Comment by jkeljo** [comment]
Hmmm... are these channels configured for net metering, by chance?

**Comment by rjsmith0** [comment]
My channels were were not setup for net metering but I was using the NET protocol.  It was working fine for a couple weeks though.  After my re-setup, I did switch back to BIN48-ABS and it is currently working.  Switching to BIN48-ABS before the re-setup didn't fix anything though.

**Comment by nivfreak** [comment]
I'll drop a couple screenshots here of config in case it's something subtle. I've now tried Bin48-Net-Time, Bin32 Net, and Bin48 ABS. I reloaded the integration and restarted HA after each packet format change, and waited 30+ minutes to see if an Energy value would populate. 

Nothing exciting in the logs either:
2023-08-31 15:35:23.963 DEBUG (MainThread) [greeneye.monitor] Packet processor started
2023-08-31 15:35:23.971 INFO (MainThread) [greeneye.monitor] Server started on 0.0.0.0:8000
2023-08-31 15:35:28.307 INFO (MainThread) [greeneye.monitor] Discovered new monitor: 1100407
2023-08-31 15:35:28.477 INFO (MainThread) [greeneye.monitor] Configured 1100407 from settings API call.
2023-08-31 15:35:28.482 INFO (MainThread) [custom_components.greeneye_monitor.sensor] Set up sensors for new monitor 1100407
2023-08-31 15:35:28.482 INFO (MainThread) [custom_components.greeneye_monitor.number] Added configuration entities for new monitor 1100407

![image](https://github.com/jkeljo/hacs-greeneye-monitor/assets/271317/f4d1b9bb-cce8-44ea-822a-f686b745f914)
![image](https://github.com/jkeljo/hacs-greeneye-monitor/assets/271317/3e954ba3-b229-486d-8985-cb22b78ff80e)
![image](https://github.com/jkeljo/hacs-greeneye-monitor/assets/271317/dbce572b-da27-493d-a524-6208bd3c07f7)

**Comment by jkeljo** [comment]
The latest version of this integration (2023.9.03) supports downloading diagnostic information and debug logs, which I hope will help me diagnose this issue more quickly. To use it, do the following:

1. In Home Assistant, go to Settings -> Devices & Services -> GreenEye Monitor (GEM).
2. Under "Hubs", find "GreenEye Monitor (GEM)", click the three dots, then click "Download diagnostics"
3. Drag-and-drop the downloaded file into a comment on this issue. It will upload the file and insert a link.
4. After downloading diagnostics, click "Enable debug logging"
5. In the three dots menu, click "Reload"
6. Return to your overview dashboard and wait until data starts to come in from all of your GEMs
7. Return to the settings screen and click "Disable Debug Logging". It will download a log file.
8. Drag-and-drop the downloaded log file into a comment on this issue. It will upload the file and insert a link.

Thanks!

**Comment by nivfreak** [comment]
Thank you. Updated to 2023.9.03. Attached are the diagnostic and debug logs.
[config_entry-greeneye_monitor-6421c9fa6902bc34aae456fbdee7dcf4.json (1).txt](https://github.com/jkeljo/hacs-greeneye-monitor/files/12507941/config_entry-greeneye_monitor-6421c9fa6902bc34aae456fbdee7dcf4.json.1.txt)
[home-assistant_greeneye_monitor_2023-09-03T22-23-53.885Z.log](https://github.com/jkeljo/hacs-greeneye-monitor/files/12507942/home-assistant_greeneye_monitor_2023-09-03T22-23-53.885Z.log)

**Comment by jkeljo** [comment]
@nivfreak perfect! One thing that jumps out at me is that the integration is configured to treat all channels as net-metered, but the GEM is not. Do you recall what the Home Assistant config UI looked like when you did your setup? It should have defaulted to all channels *not* net metered, such that you would have had to check a bunch of boxes to get into this situation, but if that didn't happen that's a bug I'd need to look into.

As I looked at this, though, I realized that I can probably change the integration so that you don't have to tell it about net metering at all, which would make this problem moot. I'll look into that.

**Comment by nivfreak** [comment]
I would say no, but it's possible I missed the label and thought I was enabling channels. I go through setup again and see if it's familiar.

**Comment by nivfreak** [comment]
Ok, now I'd say it's likely! Looks like I have energy information flowing. Thank you!

**Comment by rjsmith0** [comment]
Looks good on my end also!  Thank you!

**Comment by jkeljo** [comment]
Awesome, glad you're both up and running! I'll close this issue now.
