### ISSUE TITLE
Support for legacy serial interface on ECM-1240

### ISSUE THREAD

**Issue by 42Network** [jkeljo/hacs-greeneye-monitor#32]
Add support for ECM-1240 serial communications

I have three ECM-1240 devices monitoring 20 circuits plus main (21 channels total) in my circuit panel. I have a custom solution using a tweaked version of Matt Wall's btmon.py sending MQTT values into HA & InfluxDB. I have an ugly Excel spreadsheet which generates the Homeassistant MQTT discovery messages for the 21 channels. These btmon.py scripts run on an RPi with a quad USB-to-serial cable that plugs into the three ECM-1240 (one serial port is used) and the RPi sends the power metrics to HA. All these scrips are stared automatically using Systemd.

I would love to move to a more officially supported solution, such as this HACS repository, but none of my ECM-1240s are "on the network" and cannot dump values to a TCP listener.

Can you think of a way to use your HACS solution in my case? 

Thanks

**Comment by sdwilsh** [comment]
I haven't had a lot of time for that project to update it with our latest changes in the upstream, but it shouldn't be too hard to do either!

**Comment by jkeljo** [comment]
I'm closing this issue since I think that other project should cover your needs. Feel free to reopen if you want to continue discussing it here.
