### ISSUE TITLE
Configuration is lost, and I cannot re-add it.

### ISSUE THREAD

**Issue by dallingham** [jkeljo/hacs-greeneye-monitor#33]
The integration lost track of my gem controller. I can still log into the GEM interface and see all the data, but the integration is saying that everything is unavailable. The device serial number is not in the configure per-monitor options list is empty.

I've tried reloading the integration, but it had no effect. I now have one hub that has nothing in it and cannot be edited.

Looking at the diagnostic, the entities seem to have been deleted but still exist in the "deleted_entities" category. I've tried removing the integration, and starting over, but I've had no luck. I even re-entered the old style gem configuration in homes that this integration would find it and reload the data. No luck.

Drag and drop your downloaded diagnostics file here:

## Debug Logs

[config_entry-greeneye_monitor-62aea2d9cfb20eae29060abac08e45c1.json.txt](https://github.com/jkeljo/hacs-greeneye-monitor/files/12515730/config_entry-greeneye_monitor-62aea2d9cfb20eae29060abac08e45c1.json.txt)

Drag and drop your downloaded log file here:
[home-assistant_greeneye_monitor_2023-09-04T17-48-40.984Z.log](https://github.com/jkeljo/hacs-greeneye-monitor/files/12515732/home-assistant_greeneye_monitor_2023-09-04T17-48-40.984Z.log)

**Comment by jkeljo** [comment]
The diagnostics show that no monitors have connected to your Home Assistant instance. I would suggest double-checking your GEM's configuration to make sure it's still sending packets to the right place (did the IP address of your Home Assistant change, maybe?). Make sure you click "Exit Setup Mode" and see the message saying it exited successfully or else it won't resume sending packets.

**Comment by dallingham** [comment]
Oddly enough, after several reboots of home assistant, the values came back.

**Comment by dallingham** [comment]
Discovered the source of the issue. When Home Assistant boots, the GEM integration is unavailable. I have to go into the GEM web interface on the device, go into setup mode, view a page, leave setup mode, then close the window I used to view the GEM web interface. At that point, the GEM devices and sensors in Home Assistant move from unavailable to reporting data.

**Comment by jkeljo** [comment]
Usually for me the packets start flowing within a few seconds after startup, but I've definitely seen the GEM take a few minutes to get reconnected before. Doing what you describe gives it a nudge, but ideally you shouldn't have to do it every time you restart. If your GEM is not on the latest COM and ENG firmware versions, you might try upgrading those in case that helps.

**Comment by dallingham** [comment]
The odd thing is, this just started happening about two days ago. I've been
successfully using the GEM for over a year now.
