### ISSUE TITLE
Cannot add serial to intergration

### ISSUE THREAD

**Issue by cogleym** [jkeljo/hacs-greeneye-monitor#36]
I have an issue with a new install. If I can go to configure, edit per monitor options, I cannot add a serial. Uninstall and reinstall does not help. Is their a way to add the serial to a config file somewhere?

**Comment by jkeljo** [comment]
The integration lists the serial numbers of all monitors that have connected to your Home Assistant. If one of your monitors is not listed, it's because that monitor has not yet sent any data packets. Double-check its configuration to make sure it's sending to the correct host and port.

**Comment by cogleym** [comment]
I fixed it. Had to use wireshark and figure out a packet issue. Switch was blocking data thinking it was a ddos or something.
