### ISSUE TITLE
Support Bin48Net -time packets

### ISSUE THREAD

**Issue by adamalli7** [jkeljo/hacs-greeneye-monitor#40]
Currently as far as I can tell this only supports the Bin32Net packets.  Is there a way we could support the BIN48NET - TIME packets?  The reason for the ask is I use the BTMON python script to retrieve data from my GEM device and then save the parsed data to influxdb. This script works as a client and requests data from the GEM, It can only work with the BIN48 format. I know people will save why don't I just save from HA to influxdb, but I mess around with my installation to much and the BTMON method works better for long term archival purposes. 

So the problem is I can't have BTMON and HA getting data at the same time as I can only set one packet format.

**Comment by jkeljo** [comment]
Oh it definitely supports BIN48_NET_TIME. What behavior are you seeing that made you think it didn't? Can you include a diagnostic dump and debug logs?

**Comment by adamalli7** [comment]
Right now I have the packet type set to BIN48NET - TIME and the GEM network utility setup to send data to my HA install.
<img width="419" alt="GEM setup" src="https://github.com/jkeljo/hacs-greeneye-monitor/assets/47260506/c75d2f7f-2329-473d-88c2-c88c724cd30a">
With this setup the GEM setup in HA appears to never receive or setup the channels
<img width="541" alt="ha" src="https://github.com/jkeljo/hacs-greeneye-monitor/assets/47260506/d6062f44-86af-4362-99f4-4fbc1d6de96f">

If I change the packet type to BIN32NET, it picks it up right away and set ups the channels.

Not sure how to do the diagnostic dump or get the debug logs.

**Comment by jkeljo** [comment]
Follow the instructions here for diagnostics and debug logs: https://github.com/jkeljo/hacs-greeneye-monitor/blob/main/.github/ISSUE_TEMPLATE/issue.md?plain=1

In step 3 of collecting the debug logs, go set your GEM back to BIN48-NET-TIME and give it a few minutes before moving to step 4.

**Comment by adamalli7** [comment]
Just letting you know I haven't forgotten about this. My hardware that was running HA just died on me, so it will be awhile before I can get back on this.

**Comment by adamalli7** [comment]
You can close this ticket. This was a misunderstanding on my part about what data was being displayed in HA. Everything is working as it should.
