### ISSUE TITLE
Initial Config Failure

### ISSUE THREAD

**Issue by maxcadrin** [jkeljo/hacs-greeneye-monitor#44]
So I truly feel like an idiot but I have a an Ethernet Only GEM (GEM-E) which I have recently installed. I can connect via the Network Utility, access the browser set up, and I can access live data from GEM NU but I can't figure out for the life of me how to get the integration to detect my GEM. I looked on the Brultech forums but they seem to reference the old integration so I don't know if I am supposed to make a yaml entry or not.

When I try to hit configure in the integration I receive the following error:

Config flow could not be loaded: {"message":"Handler does not support user"}

So all I have is the hub but no discovery. What am I doing wrong? Did I miss documentation somewhere? Should I be creating that initial yaml entry, posts seem to suggest not but I am lost at this point?

**Comment by jkeljo** [comment]
Thanks for reporting the issue with the Configure button; I'll look into that.

Looking over the docs for this integration in HACS, I realized that there are some details that were present in the docs for the built-in integration that didn't get translated over. I'll look into putting that somewhere as well.

When you first added the integration, it would have asked you for a port number. You have to set your GEMs packet format to one of the binary formats (for example, “Bin32 NET” for a 32-channel GEM with some channels configured for net metering) in the "Packet Send" page of the GEM UI. Then in the "Network" page, enter the hostname or IP address of your home assistant machine, and the same port number that you put in when you added the integration. Once packets are arriving, the integration will automatically add entities for them and you can proceed to customize them (renaming, etc.) from there.

**Comment by jkeljo** [comment]
Make sure to click "Exit Setup Mode" as well, or it won't start sending the packets.

**Comment by maxcadrin** [comment]
Alright, so I had found the whole packet type initially and configured it correctly but the network is where I get confused. I have to use the GEM Network utility to set things up since attempting to go into the network tab gives me a message to configure my GEM with the network utility. Now I imagine I need to configure the correct IP in the Network Utility but I see any "remote host option". The Network Utility has client or server and while I have tried playing both settings nothing seems to change in the integration.

**Comment by jkeljo** [comment]
Unfortunately I've never used the network utility, but looking at the screenshot on page 4 of [the manual](https://www.brultech.com/software/files/downloadSoft/Ethernet_Setup_ver_3..pdf) I think you want to enter your home assistant info in the Server IP/Remote Port boxes and then set Ethernet mode to "mixed".

**Comment by maxcadrin** [comment]
So that isn't it. I tried it but got nothing back. Is it normal that I cannot click "configure" on the GEM hub within the integration? I get that error message I mentioned in my earlier post. Otherwise, I can see live data no problem within the utility and I can connect directly. I will try to reach out on the Brultech forums as well for info on how to configure remote hosts with an ethernet only board (which requires the use of the utility) but I just wanted to make sure there was no problem with my integration or its setup.

**Comment by jkeljo** [comment]
Yes the Configure button failure is normal, or at least it happens to me too. I feel like that used to work differently, but who knows. I'll see about fixing it next time I have some free time to work on this.

I'll probably also look into making the initial setup a bit smarter; setup issues seem to be pretty common.

**Comment by jkeljo** [comment]
5.0.2 is the version of the Python library that the integration uses, not related to firmware.

Can you upload diagnostic logs for the integration? Maybe there's something in there.

Might be worth trying a different port, in case there's something else on your home assistant instance using port 8000. You'd need to remove and re-add the integration in order to get the chance to select a new port, and you'd need to update your GEM's remote configuration to send to that.

Otherwise, maybe there's something network related, like if the GEM is on a switch port with port isolation on or otherwise not able to reach your HA instance.

**Comment by maxcadrin** [comment]
I am able to ping the GEM from the HA instance so that last option is not it. I tried different ports to no avail, checking which ports are currently in use. I will upload the diagnostic logs for the integration tomorrow night if I don't find the issue by then.

**Comment by maxcadrin** [comment]
[config_entry-greeneye_monitor-2a5ec0d8cdff376c77f215925afbfddf.json](https://github.com/jkeljo/hacs-greeneye-monitor/files/14471184/config_entry-greeneye_monitor-2a5ec0d8cdff376c77f215925afbfddf.json)

Here is the diagnostic logs. I did a couple checks with Brultech and we concluded that everything is fine on the config side. For some reason, it seems like the integration isn't trying to reach out to the GEM. You will see on the diagnostics that I tried changing the port to a random 8k port. I also attempted with the port 8000 to no avail so it isn't the port number.

**Comment by jkeljo** [comment]
To be clear, it's the GEM that reaches out to the integration.

The diagnostic dump you sent shows it's listening on port 8698; I assume that's the random 8k port you used?

Are there any errors from the integration in the HA system log?

Can you also enable debug logging, let it run for a few minutes and then send those too? I'm wondering if it is receiving malformed packets or failing to open the port or something like that.

**Comment by maxcadrin** [comment]
[home-assistant_greeneye_monitor_2024-03-03T01-46-06.374Z.log](https://github.com/jkeljo/hacs-greeneye-monitor/files/14471356/home-assistant_greeneye_monitor_2024-03-03T01-46-06.374Z.log)

Here you go. Apologies for earlier, I was mixed up, the GEM is indeed the client reaching out to the HA integration.

**Comment by jkeljo** [comment]
No smoking guns there... the last line in the log is the integration starting to listen on the port, but then nothing comes in.

I'm a bit stumped. At this point all I've got is to triple check that you've got the HA IP address right in the GEM config, that it's actually configured to send packets, that the packet interval is something pretty short (5 seconds, say), and that you click "Exit Setup Mode" after doing all of that.

Are you comfortable with running terminal commands on your computer (not the HA machine)? If so I can give you a few things to try to narrow things down.

**Comment by maxcadrin** [comment]
Yeah, I am comfortable doing that. I will triple check my settings as you mentioned. Let me know if there is anything you think I can run to narrow it down.

**Comment by jkeljo** [comment]
Set real-time status to ON; without that it won't send packets

**Comment by maxcadrin** [comment]
The smoking gun. Why I didn't set it to ON is beyond me. Thanks for the info, it is now discovered. So sorry for such a dummy oversight.

**Comment by maxcadrin** [comment]
Thanks for all the help.
