### ISSUE TITLE
Error Handler OptionsFlowManager doesn't support step options_menu

### ISSUE THREAD

**Issue by StephenShamakian** [jkeljo/hacs-greeneye-monitor#47]
## Describe the bug

When I click the configure button in HA Integrations for the Greeneye Monitor I get this error:

`Error
Config flow could not be loaded: {"message":"Handler OptionsFlowManager doesn't support step options_menu"}`

## Diagnostics

[config_entry-greeneye_monitor-dfe89aa8935a6d0aef6defb7a33e2c1e.json](https://github.com/user-attachments/files/17532639/config_entry-greeneye_monitor-dfe89aa8935a6d0aef6defb7a33e2c1e.json)

**Comment by StephenShamakian** [comment]
Any update on this? Thanks!

**Comment by jkeljo** [comment]
It’s a known issue. There are no configurable options after initial setup.

**Comment by StephenShamakian** [comment]
How do you add a second GEM monitor then? I got 2 more since the first one.

**Comment by StephenShamakian** [comment]
@jkeljo any way to add additional GEMs to an already configured integration? As I ordered two more and am unsure how to get this integration to recognize them.

**Comment by jkeljo** [comment]
Just configure the second GEM to send packets to the same port on your Home Assistant that the first one is using. Once it starts receiving packets, the integration will give you the option to set up the new device.

**Comment by StephenShamakian** [comment]
I have the dashbox forward all GEM packets to Home Assistant. But the second GEM is not appearing in HA. Only the original first GEM is.

**Comment by jkeljo** [comment]
Double check the packet format is the same as the GEM that works (needs to be one of the binary formats). If that doesn't work, can collect some debug logs and send them to me?

**Comment by StephenShamakian** [comment]
I'm actually all set now! 

I opened a support case with BrulTech and they got me sorted out with getting the GEM to communicate correctly to the Dashbox. After doing that it properly appeared like you said in HA.

Thanks!
